# Generated by Django 3.2.4 on 2021-08-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='作者名称')),
                ('Gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别')),
                ('Bron_Date', models.CharField(max_length=20, verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '作者表',
                'db_table': 'tb_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=20, verbose_name='书籍名字')),
                ('Publish_Date', models.CharField(max_length=20, verbose_name='发表日期')),
                ('Country', models.CharField(max_length=20, verbose_name='所属国家')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.author', verbose_name='所属作者')),
            ],
            options={
                'verbose_name': '图书表',
                'db_table': 'tb_book',
            },
        ),
    ]
